### PR TITLE
Added a  new theme based on song and added a page with the coorespond…

### PR DESCRIPTION
**Pull request by priyanshu-gupta0503**
…ing audio player of that particular song

### CODE REVIEW

**Review by omicreativedev — CHANGES_REQUESTED** [review]
Nice work! I have a small change request:

- Update your branch before PR
- Only PR your Page, Theme, Pages_list.txt, and Theme_list.txt
- Remove index.html and .vscode/settings from your PR
- Check that themes_list.txt has no conflicts after branch update
Fixes #19

Let me know if you need some help but it looks like you know what you're doing :)

I await the small update. Everything looks good otherwise.

**Comment by priyanshu-gupta0503** [comment]
sure I will do it.

**Comment by priyanshu-gupta0503** [comment]
hey@omicreativedev pls help me with your request as i tried many things but was not able to come to the required outcome.

**Comment by priyanshu-gupta0503** [comment]
hey @omicreativedev  I messed up some things during merging so I deleted the repo so that I can restart but I am not able to understand anything Pls guide me.

**Pull request closed without merging**
